// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdf9DMSY19S0wrmqDjfXLrw_qsEHdTkY',
    appId: '1:651843039556:web:1766e205c52e901f07a711',
    messagingSenderId: '651843039556',
    projectId: 'chat-app-713cf',
    authDomain: 'chat-app-713cf.firebaseapp.com',
    storageBucket: 'chat-app-713cf.appspot.com',
    measurementId: 'G-3DN86MYFR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Qv8fT5a2s7AZuSfOKfdB0nXRsTym4sk',
    appId: '1:651843039556:android:f4973cdbc8eabab507a711',
    messagingSenderId: '651843039556',
    projectId: 'chat-app-713cf',
    storageBucket: 'chat-app-713cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28qnULK8QQozaGYd_jjAoMA6fPoZzk5A',
    appId: '1:651843039556:ios:14d36fe9e4bafdb407a711',
    messagingSenderId: '651843039556',
    projectId: 'chat-app-713cf',
    storageBucket: 'chat-app-713cf.appspot.com',
    iosClientId: '651843039556-le17lc7cmlds342ei8lljp0mjat2412i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA28qnULK8QQozaGYd_jjAoMA6fPoZzk5A',
    appId: '1:651843039556:ios:14d36fe9e4bafdb407a711',
    messagingSenderId: '651843039556',
    projectId: 'chat-app-713cf',
    storageBucket: 'chat-app-713cf.appspot.com',
    iosClientId: '651843039556-le17lc7cmlds342ei8lljp0mjat2412i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}